# JPA Setting
spring:
  jpa:
    hibernate:
      ddl-auto: create

      # bulk date insert or update Batch Process Enable
      jdbc.batch-auto: 100
      order-insert: true
      order-update: true


    database: mysql
    database-plattform: org.hibernate.dialect.MySQL8Dialect

    # SQL logger
    show-sql: true
    properties.hibernate.format_sql: true
