# JPA Setting
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    propertices:
      hibernate:
        jdbc.batch_size: 50
        order_insert: true
        order_update: true
        format_sql: true

    hibernate:
      ddl-auto: create
    show-sql: true
